"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Djolar = exports.WebStyleSearcherAdapter = exports.defaultWebSearchFunc = exports.GoMicroStyleSearcherAdapter = exports.defaultGoMicroSearchFunc = void 0;
var adapter_go_micro_1 = require("./adapter_go_micro");
Object.defineProperty(exports, "defaultGoMicroSearchFunc", { enumerable: true, get: function () { return adapter_go_micro_1.defaultGoMicroSearchFunc; } });
Object.defineProperty(exports, "GoMicroStyleSearcherAdapter", { enumerable: true, get: function () { return adapter_go_micro_1.GoMicroStyleSearcherAdapter; } });
var adapter_web_1 = require("./adapter_web");
Object.defineProperty(exports, "defaultWebSearchFunc", { enumerable: true, get: function () { return adapter_web_1.defaultWebSearchFunc; } });
Object.defineProperty(exports, "WebStyleSearcherAdapter", { enumerable: true, get: function () { return adapter_web_1.WebStyleSearcherAdapter; } });
var Djolar = require("./djolar");
exports.Djolar = Djolar;
var searcher_1 = require("./searcher");
exports.default = searcher_1.default;
